//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class booktran
    {
        public string BookID { get; set; }
        public string MemberID { get; set; }
        public Nullable<System.DateTime> LendDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> LendRate { get; set; }
        public Nullable<int> Fine { get; set; }
        public string Balance { get; set; }
        public Nullable<int> RenewalDays { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LibBal { get; set; }
        public Nullable<int> MemBal { get; set; }
        public int TRANSID { get; set; }
    }
}
