//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int FineID { get; set; }
        public int FineAmt { get; set; }
        public Nullable<System.DateTime> FineDate { get; set; }
        public string MemberID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
