//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibEntities : DbContext
    {
        public LibEntities()
            : base("name=LibEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BookPurchase> BookPurchases { get; set; }
        public DbSet<Series> Series { get; set; }
        public DbSet<author> authors { get; set; }
        public DbSet<SubCategory> SubCategories { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<booktran> booktrans { get; set; }
        public DbSet<member> members { get; set; }
        public DbSet<WishList> WishLists { get; set; }
        public DbSet<book> books { get; set; }
        public DbSet<balance> balances { get; set; }
        public DbSet<Fine> Fines { get; set; }
    }
}
