//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public string MemberID { get; set; }
        public string MemberName { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Doj { get; set; }
        public Nullable<int> Status { get; set; }
        public string Mobile { get; set; }
        public string Landline { get; set; }
        public string Email { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> MemberType { get; set; }
        public Nullable<int> SortID { get; set; }
        public int ID { get; set; }
    }
}
