//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public string BookID { get; set; }
        public string BookName { get; set; }
        public Nullable<int> Soldprice { get; set; }
        public Nullable<int> BookPrice { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> SeriesID { get; set; }
        public Nullable<int> OrgPrice { get; set; }
        public Nullable<int> Status { get; set; }
        public string ISBN { get; set; }
    }
}
